using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraController : MonoBehaviour
{
    public static CameraController instance;

    [SerializeField]
    float moveSpeed;
    [SerializeField]
    Transform target;

    // Start is called before the first frame update
    void Awake()
    {
        instance = this;
    }

    // Update is called once per frame
    void Update()
    {
        if (target != null)
        {
            transform.position = Vector3.MoveTowards(
                transform.position, 
                new Vector3(target.position.x, target.position.y, transform.position.z),
                Time.deltaTime * moveSpeed
            );
        }
    }

    public void ChangeTarget(Transform nextTarget)
    {
        target = nextTarget;
    }
}
